# Generated by Django 5.1.4 on 2024-12-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecretSantaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_santa.kid')),
                ('secret_santa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_kid', to='secret_santa.kid')),
            ],
        ),
    ]
